# Generated by Django 5.2 on 2025-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Erode', 'Erode'), ('Vellore', 'Vellore'), ('Thanjavur', 'Thanjavur'), ('Thoothukudi', 'Thoothukudi'), ('Tirunelveli', 'Tirunelveli'), ('Dindigul', 'Dindigul'), ('Cuddalore', 'Cuddalore'), ('Kancheepuram', 'Kancheepuram'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Nagapattinam', 'Nagapattinam'), ('Ramanathapuram', 'Ramanathapuram'), ('Sivaganga', 'Sivaganga'), ('Krishnagiri', 'Krishnagiri'), ('Namakkal', 'Namakkal'), ('Perambalur', 'Perambalur'), ('Pudukkottai', 'Pudukkottai'), ('Theni', 'Theni'), ('Villupuram', 'Villupuram'), ('Virudhunagar', 'Virudhunagar')], max_length=100),
        ),
    ]
